### ISSUE TITLE
[Windows] It is nice YAML_CPP_DLL is exported by default.

### ISSUE THREAD

**Issue by seanyen** [ros2/yaml_cpp_vendor#10]
On Windows, the `yaml-cpp` is built as shared libraries. In such case, `YAML_CPP_DLL` is required to define to correctly consume the `yaml-cpp` (otherwise, [visibility decoration](https://github.com/jbeder/yaml-cpp/blob/4fb1c4b92bf8d94b32ebccdd890407d45b3bc794/include/yaml-cpp/dll.h#L19) won't be defined and it results in linkage time error).

And currently every project consuming `yaml-cpp` will need to define it in their CMake project to enable Windows build. It would be nice to see this exported directly from this package and all the downstream project can get the definition for free.

UPDATED:
For example,
* https://github.com/ros-perception/image_common/blob/ros2/camera_calibration_parsers/src/parse_yml.cpp#L49
* https://github.com/ros2/rosbag2/blob/master/rosbag2_transport/src/rosbag2_transport/recorder.cpp#L36
* https://github.com/ros2/rviz/blob/ros2/rviz_common/src/rviz_common/yaml_config_reader.cpp#L42

And I discovered this issue when I try to [enable navigation2](https://github.com/ros-planning/navigation2/pull/1704) on Windows.

**Comment by dirk-thomas** [comment]
@seanyen Please provide a pull request to add the necessary definition to the `ExternalProject_Add` call.

**Comment by dirk-thomas** [comment]
Please also describe your exact steps when you run into problem since afaik we are currently able to use this package as is on Windows without problems.

**Comment by seanyen** [comment]
Thanks for the pointer. I will be looking how to export it from `ExternalProject_Add` and I added some examples how does it affect the downstream projects.

**Comment by dirk-thomas** [comment]
So everything works fine atm but you propose a change in order to be able to remove these workarounds in other packages. That wasn't clear from the original description. Sounds good to me.

Please also make pull requests for the referenced packages so that it can be checked that the to-be-proposed change makes today workarounds obsolete.

**Comment by hidmic** [comment]
Are you still picking this up @seanyen ?

**Comment by dirk-thomas** [comment]
@seanyen Friendly ping.

**Comment by clalancette** [comment]
This should now be solved on the latest with #25 being merged.  It should also be solved in Galactic and Foxy with PRs #30 and #31, so I'm going to go ahead and close this out.

**Comment by Ace314159** [comment]
@clalancette I see #30 and #31 haven't been merged yet. Are there plans to merge them or is something holding them up?

**Comment by jacobperron** [comment]
I've approved and triggered Windows CI for #30 and #31.

**Comment by jacobperron** [comment]
Circling back here, it's not clear that https://github.com/ros2/yaml_cpp_vendor/pull/25 actually resolved this issue since removing the YAML_CPP_DLL patches in connected PRs results in a build failure.

Connected PRs:
- https://github.com/ros2/rviz/pull/831
- https://github.com/ros2/rosbag2/pull/964

Maybe there's something else missing in the downstream packages.
