### ISSUE TITLE
Cross-compiling the package

### ISSUE THREAD

**Issue by alsora** [ros2/yaml_cpp_vendor#5]
Hi, I'm cross-compiling this package for RaspberryPi raspbian OS.

I'm able to cross-compile all the ROS2 SDK packages, however the output of this package are some x86_64 libraries.

Do you know how to fix it?

Thanks

**Comment by dirk-thomas** [comment]
I am not sure if you have seen the [ROS support guidelines](http://wiki.ros.org/Support) but we kindly ask to raise questions like this on [answers.ros.org](http://answers.ros.org/) instead.

The rational for asking all kind of questions in a single place is:
* There are many more people reading questions there so your chances on getting an answer and in a timely manner are much higher.
* In the future other users will search there for similar problems and can find your question and the potential answers.
* The issue tracker in this repo is used to track bugs, feature requests, etc. But your question is not such an action item.

Therefore I will close this ticket here for now. If you have asked your question on answers.ros.org please feel free to add a link to the question to this ticket so that future readers can find the related question.

**Comment by alsora** [comment]
Sorry the ticket is not well formulated.
However, to me this clearly looks like a bug.

The `CMakeLists.txt` file of this package is not checking for the presence of a toolchain file as the other ROS2 vendor packages are doing

https://github.com/ros2/poco_vendor/blob/master/CMakeLists.txt#L22

**Comment by dirk-thomas** [comment]
> Let me know what do you think and I can work on a PR

Any pull request are welcome. Please make sure to include enough information to reproduce your use case in order to be reviewable.

**Comment by alsora** [comment]
Closing, as this is issue is addressed by last commit https://github.com/ros2/yaml_cpp_vendor/commit/d7a96580ae1b786ec6b46a81c8fc8ef6624eae21
